version: "3.9"
# you can run multiple services inside one docker compose file
# define them with their dependencies one after the other
services:
  webber-crm-ui-dev:
    container_name: webber-crm-ui-dev
    build:
      context: .
      dockerfile: ./dockerfiles/development/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development
