version: "3.9"
# you can run multiple services inside one docker compose file
# define them with their dependencies one after the other
services:
  dev:
    container_name: webber-crm-ui_dev
    build:
      context: .
      dockerfile: ./dockerfiles/development/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development

  prod:
    container_name: webber-crm-ui_prod
    build:
      context: .
      # the dockerfile to be run
      dockerfile: ./dockerfiles/production/Dockerfile
    ports:
      - "80:8080"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=production
